import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from '@/lib/auth';
import { connectDB, Idea } from '@tds/database';

export const dynamic = 'force-dynamic';

// GET /api/tools/ideation/[id]/export — Export PRD as markdown
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    await connectDB();

    const idea = await Idea.findById(id).lean();
    if (!idea) {
      return NextResponse.json({ error: 'Idea not found' }, { status: 404 });
    }

    const prdData = idea.stages.prd.extractedData as Record<string, unknown>;
    let markdown = '';

    if (prdData?.fullMarkdown) {
      markdown = prdData.fullMarkdown as string;
    } else if (prdData?.sections) {
      const sections = prdData.sections as Array<{ title: string; content: string }>;
      markdown = `# ${prdData.title || idea.title}\n\n`;
      if (prdData.summary) {
        markdown += `${prdData.summary}\n\n---\n\n`;
      }
      for (const section of sections) {
        markdown += `## ${section.title}\n\n${section.content}\n\n`;
      }
    } else {
      // Fallback: use the last assistant message from PRD stage
      const prdMessages = idea.stages.prd.messages;
      const lastAssistant = [...prdMessages].reverse().find((m) => m.role === 'assistant');
      markdown = lastAssistant?.content || 'No PRD content available.';
    }

    // Add metadata footer
    markdown += `\n\n---\n*Generated by TDS Ideation Tool on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*\n`;

    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${idea.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-prd.md"`,
      },
    });
  } catch (error) {
    console.error('Error exporting PRD:', error);
    return NextResponse.json({ error: 'Failed to export PRD' }, { status: 500 });
  }
}
